[package]
name = "day-two"
version = "0.1.0"
authors = ["Robin Miller <grenewodemiller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path = "../intcode" }
